export const en = {
  meta: {
    title: 'Supercycl Mobile Launch Festival',
    tagline: 'TRADE DIFFERENT · RIDE THE SUPERCYCL',
    period: 'Jun 8 – Jul 7, 2026 · 1 MONTH',
  },
  cta: {
    joinNow: 'Join now',
    tradeNow: 'Trade now',
    startSurvey: 'Start survey',
    registerUsdt: 'Register USDT info',
    registerIcx: 'Register ICX wallet',
    viewTerms: 'View terms',
    goToMain: 'Open Supercycl app',
  },
  rewards: {
    heading: 'Rewards',
    usdtLine: 'Trade $500: 20 USDT',
    icxLine: 'Complete survey: ICX reward',
    usdtCardTitle: '20 USDT — Trade $500',
    icxCardTitle: 'ICX — Complete survey',
  },
  steps: {
    heading: 'How to participate',
    step1: 'Sign up + connect exchange',
    step2: 'Trade $500 → 20 USDT',
    step3: 'Complete the 13-question survey → ICX',
  },
  slot: {
    label: 'Trading slots remaining',
    suffix: '/ 500',
  },
  progress: {
    heading: 'My progress',
    volume: (vol: number) => `Cumulative volume $${vol} / $500`,
    remaining: (rem: number) => `${rem > 0 ? `$${rem} to go` : 'Goal reached!'}`,
    daysLeft: (d: number) => `${d > 0 ? `${d} days until end` : 'Campaign ended'}`,
    slotsLeft: (n: number) => `${n} slots remaining`,
  },
  status: {
    locked: 'Locked',
    notRegistered: 'Registration required',
    pending: 'Pending payout',
    review: 'Under review (max 7 days)',
    completed: 'Paid',
    expired: 'Expired',
    capFull: '$500 reached — slot capacity full. Thank you.',
  },
  banner: {
    campaignRunning: (start: string, end: string) => `Supercycl Mobile Launch Festival is live (${start} – ${end})`,
    slots100: '100 slots left! Start trading now',
    slots50: '50 slots left! Don’t miss out',
    slots10: '10 slots left! Final call',
    d3: '3 days until the campaign ends',
  },
  modal: {
    survey: {
      title: 'Profile & Earn — 13 questions',
      submit: 'Submit',
      next: 'Next',
      previous: 'Back',
      completeTitle: 'Thanks for completing the survey!',
      completeBody: 'Your mini-report is below. Register your ICX wallet to receive the reward.',
      registerIcxCta: 'Register ICX wallet',
    },
    usdt: {
      title: 'How would you like to receive 20 USDT?',
      methodWallet: 'Receive to TRC20 wallet',
      methodExchange: 'Receive to exchange balance',
      trc20Label: 'TRC20 USDT wallet address',
      trc20Warning: 'Sending to a non-TRC20 network may result in loss of funds. Double-check the network.',
      networkCheck: 'I have confirmed the network',
      exchangeFixed: 'Exchange: OKX',
      okxUidLabel: 'OKX UID',
      okxEmailLabel: 'OKX registered email',
      termsCheck: 'I agree to the event terms and privacy policy',
      submit: 'Register',
    },
    icx: {
      title: 'Register your ICX wallet',
      addressLabel: 'ICON wallet address (hx…)',
      termsCheck: 'I agree to the event terms and privacy policy',
      submit: 'Register',
    },
    slotSecured: {
      title: (slot: number) => `🎉 Slot #${slot} / 500 secured!`,
      body: 'Register your USDT receiving info to claim 20 USDT.',
      cta: 'Register USDT info',
    },
    milestone: {
      title: 'Half way there!',
      body: 'Trade $250 more to lock in 20 USDT.',
    },
    nps: {
      title: 'One last question',
      body: 'How likely are you to recommend Supercycl to a friend?',
      registerReminder: 'Don’t forget to register your reward info before the cutoff.',
    },
    terms: { title: 'Event terms & privacy', close: 'Close' },
  },
  hub: {
    stepDone: 'Done',
    stepInProgress: 'In progress',
    stepLocked: 'Up next',
    icxNonTrader: 'Non-trader pool reward: TBD (pending operations decision)',
  },
  outsideWindow: {
    surveyClosed: 'Survey opens June 29',
    surveyEnded: 'Survey closed',
    registrationClosed: 'Registration closed',
  },
  errors: {
    required: 'This field is required',
    inconsistentState: 'Inconsistent mock state',
    persistenceReset: 'Mock state reset due to corruption',
  },
};

export type En = typeof en;
